trigger:
  batch: true
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

stages:

# Lint the Bicep file.
- stage: Lint
  jobs: 
  - template: pipeline-templates/lint.yml

# Deploy to the test environment.
- template: pipeline-templates/deploy.yml
  parameters:
    environmentName: NonProd
    environmentType: toy-webapp-non-prod
    #resourceGroupName: rg-webapp-nonprod-yrhpwc
    serviceConnectionName: sctoywebappnonprodbicep

# Deploy to the production environment.
- template: pipeline-templates/deploy.yml
  parameters:
    environmentName: Prod
    environmentType: toy-webapp-prod
    #resourceGroupName: rg-webapp-prod-yrhpwc
    serviceConnectionName: sctoywebappprodbicep