trigger:
  batch: true
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

  stages:
    - stage: Lint
      jobs: 
      - job: LintCode
        displayName: Lint code
        steps:
          - script: |
              az bicep build --file deploy/main.bicep
            name: LintBicepCode
            displayName: Run Bicep linter

    - stage: Validate
      jobs: 
      - job: ValidateBicepCode
        displayName: Validate Bicep code
        steps:
        - task: AzureCLI@2
          name: RunPreflightValidation
          displayName: Run preflight validation
          inputs:
            azureSubscription: $(ServiceConnectionName)
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az deployment group validate \
                --resource-group $(ResourceGroupName) \
                --template-file deploy/main.bicep \
                --parameters environmentType=$(EnvironmentType)
            
    - stage: Deploy
      jobs:
      - job: Deploy
        steps:
          - task: AzureCLI@2
            name: Deploy
            displayName: Deploy to Azure
            inputs:
              azureSubscription: $(ServiceConnectionName)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az deployment group create \
                  --name $(Build.BuildNumber) \
                  --resource-group $(ResourceGroupName) \
                  --template-file deploy/main.bicep \
                  --parameters environmentType=$(EnvironmentType)